### ISSUE TITLE
Can show file in other target? (_self, _blank, etc) 

### ISSUE THREAD

**Issue by alebulo** [lorenzos/Minixed#12]
Can make that file to click show in other target or popup? where need to make a parameter? (sorry my bad english) Thank!!

**Comment by lorenzos** [comment]
You can edit [line 378](https://github.com/lorenzos/Minixed/blob/master/index.php#L378) and add `target="_blank"` just after `<a `, simple as that. Let me know if it works!

```html
// Before
<a href="<?php echo htmlentities($itemURL) ?>" class="name <?php if ($showIcons) echo $item['isdir'] ? 'directory' : 'file' ?>"><?php echo htmlentities($item['name']) . ($item['isdir'] ? ' /' : '') ?></a>

// After
<a target="_blank" href="<?php echo htmlentities($itemURL) ?>" class="name <?php if ($showIcons) echo $item['isdir'] ? 'directory' : 'file' ?>"><?php echo htmlentities($item['name']) . ($item['isdir'] ? ' /' : '') ?></a>
```

**Comment by alebulo** [comment]
Work , but when click on folder, open in pop up too....can open only  in "_blank" a file archive when I click on it? can discriminate for extension? (like open only .pdf in "_blank" target...
And other question, a file with " ü, é, á, í, ó, ú, ñ, Ñ " in the name don show...a problem with charset appear...put ` <meta charset="UTF-8">` in all places, but don't work...here a picture
![1](https://user-images.githubusercontent.com/84341026/118665747-f19ef200-b7c8-11eb-959e-e017750585c5.jpg)

Thank you for your time!!! this  php is amazing....

**Comment by lorenzos** [comment]
Reopening it for the charset issue. Will look into it asap. If you happen to fix it yourself before, post the solution here.

To use `target="_blank"` only for files you could try using the `$item['isdir']` flag, for example:

```html
// After
<a <?php echo $item['isdir'] ? '' : 'target="_blank"' ?> href="<?php echo htmlentities($itemURL) ?>" class="name <?php if ($showIcons) echo $item['isdir'] ? 'directory' : 'file' ?>"><?php echo htmlentities($item['name']) . ($item['isdir'] ? ' /' : '') ?></a>
```

**Comment by lorenzos** [comment]
@alebulo I made a test for the filenames issue, and I found that everything works correctly on my end (see below). Maybe you need to tweak your web server settings?

![immagine](https://user-images.githubusercontent.com/245615/118791873-693b5280-b897-11eb-8785-61ae3fc581c3.png)

**Comment by alebulo** [comment]
The target changed work perfectly!!!! thank you!!! but not the acent....i work with xampp....let me see if i have somethig worng in other files....thank you for your time!!!!

**Comment by alebulo** [comment]
Sorry..but i try everithing iin XAMPP and don't see names with special characters, so......if possible to force a charset to UTF-8 in this part?:
`<a href="<?php echo htmlentities($itemURL) ?>" class="name <?php if ($showIcons) echo $item['isdir'] ? 'directory' : 'file' ?>"><?php echo htmlentities($item['name']) . ($item['isdir'] ? ' /' : '') ?></a>`
Thank you for you time...

**Comment by alebulo** [comment]
I FOUND A SOLUTION!!!! This is that I do, only change:

`<a href="<?php echo htmlentities($itemURL) ?>" class="name <?php if ($showIcons) echo $item['isdir'] ? 'directory' : 'file' ?>"><?php echo htmlentities($item['name']) . ($item['isdir'] ? ' /' : '') ?></a>`

for this:

`<a <?php echo utf8_encode($item['isdir']) ? '' : 'target="principal"' ?> href="<?php echo htmlentities(utf8_encode($itemURL)) ?>" class="name <?php if ($showIcons) echo utf8_encode($item['isdir']) ? 'directory' : 'file' ?>"><?php echo htmlentities(utf8_encode($item['name'])) . (utf8_encode($item['isdir']) ? ' /' : '') ?></a>`

Add parameter UTF-DECODE in all variables ...thank you fo rall!!!

**Comment by lorenzos** [comment]
@alebulo Great! Sorry if I didn't help you on that, I couldn't reproduce the issue on my end, so I had no way to make tests. Just one suggestion, looking at your code: you surely don't need and you shouldn't do encoding on `isdir`, since it's a boolean value. Replace all the instances of `utf8_encode($item['isdir'])` to just `$item['isdir']` like it was before.

**Comment by alebulo** [comment]
You're rigth...only this part:
` echo htmlentities(utf8_encode($item['name'])) `
change the name...but if do this, a link in that file don't work..need put the encode command in some $itemdir too...
