### ISSUE TITLE
Square brackets not encoding to %5B and %5D

### ISSUE THREAD

**Issue by camAtGitHub** [lorenzos/Minixed#14]
Hello,
I'm not 100% sure, but it seems like urlencode is not working correctly for the generated index page hyperlinks.

Example some of my folders on disk contain square brackets `[` and `]` in the path name ie. `/videos/Latest.Download.1080p.[foo]/` and while most browsers manage just fine, VLC can't access the directory - unless square brackets are encoded.

I tried to briefly write my own escape function, but it only worked on strings and not buildLink().

If you have time can you have a look?

Much Love!

**Comment by lorenzos** [comment]
Thanks for reporting! Should be fixed in 6c9f29a, try updating your code and let me know!
