### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by egganoodle** [lorenzos/Minixed#16]
Hi, when I copy the code and run it, It doesnt display anything but jumbled code. It just breaks instantly?

**Comment by tim-elmer** [comment]
An example of the output you are seeing would be helpful, as well environment information like the host OS, webserver, PHP runtime, etc..

**Comment by mudza09** [comment]
When use PHP 8.1 got error like this:
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\Laragon\www\index.php on line 40

and 
Deprecated: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in C:\Laragon\www\index.php on line 109

how we can fix for this? thanks for your help

**Comment by lorenzos** [comment]
@Mudza09 Thanks for testing on PHP 8.1. Changes in 1c8090e should fix your deprecation warnings. Please test them, and let me know if you get additional warnings or errors. You can download the updated file here: https://raw.githubusercontent.com/lorenzos/Minixed/php-8.1/index.php

**Comment by mudza09** [comment]
Great, have test them and that got rid of the error, thanks mate!
