### ISSUE TITLE
Add option for files to ignore

### ISSUE THREAD

**Issue by wilbert-vb** [lorenzos/Minixed#17]
It would be great to have the option of a custom list of items that we don't want to show.
Like index.php, favicon,ico, /scripts /css

**Comment by lorenzos** [comment]
Thanks for the suggestion. I added basic support in https://github.com/lorenzos/Minixed/commit/adfbc794b451368d0681477d890133e9947b26ff, see [line 26](https://github.com/lorenzos/Minixed/blob/master/index.php#L26). Your example would be:

```php
$ignore = array('index.php', 'favicon.ico', 'scripts', 'css');
```
