### ISSUE TITLE
Inaccurate time on last modified

### ISSUE THREAD

**Issue by ghanwar** [lorenzos/Minixed#18]
Why is the last modified time in my index 7 hours longer than the current time? What's the solution?
The current time is 18.50 but the last modified time was 11.50. even though the file was just edited.

**Comment by ghanwar** [comment]
Attached picture

![minixed](https://github.com/lorenzos/Minixed/assets/76475522/40fd60a8-7df9-493d-a8d2-7612ea251c82)

**Comment by lorenzos** [comment]
It may be an issue with your timezone settings. What's the timezone in which your "current time is 18.50"? Make sure the same timezone is set as default on the system where Minixed runs; or (better?) you can try [setting it in the PHP script](https://www.php.net/manual/en/function.date-default-timezone-set.php), for example adding this as the first line of code in `index.php`:

```php
date_default_timezone_set('Europe/Rome'); // One from https://www.php.net/manual/en/timezones.php
```
