### ISSUE TITLE
special characters are not displayed

### ISSUE THREAD

**Issue by julio1501** [lorenzos/Minixed#19]
Hello,

Folder names with special charachters like ü or ö are unfortunately not displayed.

Kind regards
SoulEye

**Comment by lorenzos** [comment]
Works fine for me: http://www.lorenzostanco.com/lab/demos/Minixed-issue-19/

It may be an issue with your server locale settings. Make sure it's UTF-8 everywhere, or change the charset of the `index.php` script.
