### ISSUE TITLE
Filesizes reporting as negative amounts

### ISSUE THREAD

**Issue by CodyWarmbo-zz** [lorenzos/Minixed#2]
Currently any file over 2GB in size displays as a negative number. Looking into it myself I believe this is an issue with PHP itself but I think you'd know better than me! I've attached an image of the issue. 
![capture](https://cloud.githubusercontent.com/assets/2780686/23722536/5fa8fb18-040b-11e7-8d56-b3dedd700478.PNG)

**Comment by lorenzos** [comment]
Unfortunately this is a PHP issue with [`filesize()`](http://php.net/manual/en/function.filesize.php) returning 32-bit integers, and there's no easy workaround. /cc @urack

I'll look into @jkuchar's [BigFileTools](https://github.com/jkuchar/BigFileTools), but I don't think I'll add a whole composer dependency just for that. Maybe I can borrow some of the code and make something smaller into my script.

PRs are welcome, obviously.

**Comment by jkuchar** [comment]
BigFileTools support only getting filesize. If you want to get filesize in a cross-platform manner, I recommend including BigFileTools as a dependency as different platforms behave differently (that is why BFT has drivers)

(Version 1 is more lightweight - https://github.com/jkuchar/BigFileTools/tree/1.1.3)

**Comment by lorenzos** [comment]
@jkuchar Thank you very much. Version 1 looks like all I need, and the fact that is all in one file makes it a good candidate.

**Comment by NaruZosa** [comment]
Any progress with this issue?

**Comment by jkuchar** [comment]
You can still install this onto 64-bit machine and 64-bit php and you get it working now. ;-)

**Comment by lorenzos** [comment]
Sorry, I didn't have time to work on it. The idea was to use BFT version 1, so... PRs are welcome.

**Comment by codywarmbo** [comment]
I'm still very interested in a solution to this...

**Comment by jkuchar** [comment]
Simple - use 64-bit PHP. ;)

**Comment by codywarmbo** [comment]
Unfortunately that does not resolve the issue.

**Comment by lorenzos** [comment]
Partially fixed using `stat()` blocks count in 5ef78b0, tested working on 32bit systems supporting the `st_blksize` type (e.g. Linux).

I feel like closing this issue, working on 32bit Windows system should be very unlikely now in 2024... 😅
