### ISSUE TITLE
Pretty URL's

### ISSUE THREAD

**Issue by BuzzITUK** [lorenzos/Minixed#21]
Stubbled across this gem in my travels - Works perfectly, thank you! Just one thing I cannot get working is "Pretty URL's". 

I am using Nginx and have added the following and although it works on the root, it doesn't when navigating through folders etc. Am I doing something wrong? 

`  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_read_timeout 3600;
    fastcgi_send_timeout 3600;
    fastcgi_param HTTPS "on";
    fastcgi_param SERVER_PORT 443;
    fastcgi_pass 127.0.0.1:{{php_fpm_port}};
    fastcgi_param PHP_VALUE "{{php_settings}}";
  }`

**Comment by lorenzos** [comment]
Sorry, can't help you, I know nothing about nginx 😅
