### ISSUE TITLE
web.config showing even when set to hidden

### ISSUE THREAD

**Issue by CodyWarmbo-zz** [lorenzos/Minixed#3]
I have $showHiddenFiles = false; set as so but my web.config file made by IIS still appears. Testing with other hidden files shows that they are not hidden as well.

**Comment by lorenzos** [comment]
`$showHiddenFiles` looks for filenames starting with a dot. That's how you tell hidden files on a UNIX-like system (Linux, OS X, etc).

On Windows hidden files are defined by a special "metadata" flag, which is not readable directly via PHP. Looks like the only way to do that is by running a Windows-specific `cmd` command and look for the flag in the output, as I just read [here](http://stackoverflow.com/a/31222607/995958).

Unfortunately you likely can't run shell commands on the majority of Windows commercial hosting, which make implementing that feature in my script quite useless.

However you can try to copy the `is_hidden_file` function from the above link, and edit [line 59](https://github.com/lorenzos/Minixed/blob/master/index.php#L59) to something like this:

    if (!$show_hidden) if (is_hidden_file($path . $file) == '.') continue;
