### ISSUE TITLE
Title shows as root when browsing

### ISSUE THREAD

**Issue by tim-elmer** [lorenzos/Minixed#6]
When browseDirectories is true, the HTML title and page title show "Index of /".

The expected behavior is that the titles show "Index of /$browse/". I can fix this by adding `. $_browse . "/"` to the titles, but that's a workaround.

**Comment by lorenzos** [comment]
Good catch! I'll fix that. Anyway a PR is welcome if you want: I think it's only necessary to edit the `getTitle()` function, concatenating `$_browse` to `$_path`.
